export { IntensitySlider } from './IntensitySlider'
export { AffectiveBubbles } from './AffectiveBubbles'
export { CATAPills } from './CATAPills'
export { ScoreDisplay } from './ScoreDisplay'

// Cupping shell primitives (Phase 3)
export { SessionShell } from './SessionShell'
export { SampleTabs } from './SampleTabs'
export type { SampleTabItem } from './SampleTabs'
export { ModuleSwitcher } from './ModuleSwitcher'
export type { ModuleItem } from './ModuleSwitcher'
export { MasterControls } from './MasterControls'
export { CanvasFooter } from './CanvasFooter'
export type { NextVariant } from './CanvasFooter'

// Form primitives (Phase 3)
export { FormSection } from './FormSection'
export { Notes } from './Notes'
export { CupToggleGrid } from './CupToggleGrid'
export { BetaBadge } from './BetaBadge'

// UI primitive kit (Phase 2)
export { Button, ButtonLink } from './Button'
export type { ButtonVariant, ButtonSize, ButtonProps, ButtonLinkProps } from './Button'
export { Badge, StatusPill, ScorePill } from './Badge'
export type { BadgeTone, BadgeSize, SessionStatus } from './Badge'
export { PageHeader } from './PageHeader'
export { SearchInput } from './SearchInput'
export { Select } from './Select'
export { EmptyState } from './EmptyState'
export { Pagination } from './Pagination'
export { FilterBar } from './FilterBar'
export type { FacetOption } from './FilterBar'
export { ConfirmDialog } from './ConfirmDialog'
export { DataTable } from './DataTable'
export type { Column, Facet } from './DataTable'
export { PillTabs } from './PillTabs'
export type { PillTabItem } from './PillTabs'
export { SegmentedControl } from './SegmentedControl'
export { InfoHint } from './InfoHint'
